services:
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  pg-docker:
    image: postgres:14-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: saraweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5433:5432
    volumes:
      - db_saraweb:/var/lib/postgresql/data
    networks:
      - dev-network
  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - 5050:80
    volumes:
      - pgadmin-docker:/var/lib/pgadmin
    networks:
      - dev-network
# ====================================================================================================================
# VOLUMES
# ====================================================================================================================
volumes:
  db_saraweb:
  pgadmin-docker:

# ======================================================================================================================
# REDE
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge
